# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ttt.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TicTacToe(object):

    def setupUi(self, TicTacToe):
        # object name
        TicTacToe.setObjectName("TicTacToe")

        # size
        TicTacToe.resize(730, 775)
        TicTacToe.setMaximumSize(QtCore.QSize(730, 775))
        
        # stylesheet
        TicTacToe.setStyleSheet("background-color: #B9B8D3;")

        # grid layout
        self.gridLayout_2 = QtWidgets.QGridLayout(TicTacToe)
        self.gridLayout_2.setObjectName("gridLayout_2")

        # TEXT LABEL
        self.text = QtWidgets.QLabel(TicTacToe)
        # size
        self.text.setMinimumSize(QtCore.QSize(500, 0))
        # font
        font = QtGui.QFont()
        font.setPointSize(18)
        self.text.setFont(font)
        # stylesheet
        self.text.setStyleSheet("background-color: #759FBC;\n"
                                "border-radius: 10px;\n"
                                "border: 1.5px dashed black;")
        # allignment
        self.text.setAlignment(QtCore.Qt.AlignCenter)
        self.text.setObjectName("text")
        self.gridLayout_2.addWidget(self.text, 1, 0, 1, 1)

        # NEW GAME BUTTON
        self.new_game = QtWidgets.QPushButton(TicTacToe)
        # size
        self.new_game.setMinimumSize(QtCore.QSize(500, 50))
        # font
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.new_game.setFont(font)
        # stylesheet
        self.new_game.setStyleSheet("background-color: #49516F;\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "border-radius: 20px;\n"
                                    "border: 1px inset white;")
        # object name
        self.new_game.setObjectName("new_game")
        self.gridLayout_2.addWidget(self.new_game, 2, 0, 1, 1)

        # THE GRID
        self.grid = QtWidgets.QFrame(TicTacToe)
        # size
        self.grid.setMinimumSize(QtCore.QSize(500, 500))
        self.grid.setMaximumSize(QtCore.QSize(500, 500))
        self.grid.setBaseSize(QtCore.QSize(150, 150))
        self.grid.setFocusPolicy(QtCore.Qt.NoFocus)
        # stylesheet
        self.grid.setStyleSheet("background-color: rgb(0, 0, 0);")
        # object name
        self.grid.setObjectName("grid")
        # layout
        self.gridLayout = QtWidgets.QGridLayout(self.grid)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        # the buttons
        # 1
        self.pushButton_1 = QtWidgets.QPushButton(self.grid)
        self.pushButton_1.setMinimumSize(QtCore.QSize(160, 160))
        self.pushButton_1.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 0, 0, 1, 1)

        # 2
        self.pushButton_2 = QtWidgets.QPushButton(self.grid)
        self.pushButton_2.setMinimumSize(QtCore.QSize(160, 160))
        self.pushButton_2.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)

        # 3
        self.pushButton_3 = QtWidgets.QPushButton(self.grid)
        self.pushButton_3.setMinimumSize(QtCore.QSize(160, 160))
        self.pushButton_3.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)

        # 4
        self.pushButton_4 = QtWidgets.QPushButton(self.grid)
        self.pushButton_4.setMinimumSize(QtCore.QSize(160, 160))
        self.pushButton_4.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)

        # 5
        self.pushButton_5 = QtWidgets.QPushButton(self.grid)
        self.pushButton_5.setMinimumSize(QtCore.QSize(160, 160))
        self.pushButton_5.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)

        # 6
        self.pushButton_6 = QtWidgets.QPushButton(self.grid)
        self.pushButton_6.setMinimumSize(QtCore.QSize(160, 160))
        self.pushButton_6.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)

        # 7
        self.pushButton_7 = QtWidgets.QPushButton(self.grid)
        self.pushButton_7.setMinimumSize(QtCore.QSize(160, 160))
        self.pushButton_7.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 0, 1, 1)

        # 8
        self.pushButton_8 = QtWidgets.QPushButton(self.grid)
        self.pushButton_8.setMinimumSize(QtCore.QSize(160, 160))
        self.pushButton_8.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 1, 1, 1)

        # 9
        self.pushButton_9 = QtWidgets.QPushButton(self.grid)
        self.pushButton_9.setMinimumSize(QtCore.QSize(160, 160))
        self.pushButton_9.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 2, 1, 1)

        self.gridLayout_2.addWidget(self.grid, 0, 0, 1, 1)

        self.retranslateUi(TicTacToe)
        QtCore.QMetaObject.connectSlotsByName(TicTacToe)

    def retranslateUi(self, TicTacToe):
        """restranslateUi."""

        _translate = QtCore.QCoreApplication.translate
        # set window title  
        TicTacToe.setWindowTitle(_translate("TicTacToe", "TicTacToe"))
        
        # label set text
        self.text.setText(_translate("TicTacToe", "LET\'S START!"))

        # new game button set text
        self.new_game.setText(_translate("TicTacToe", "New Game"))

        # grid buttons set text
        self.pushButton_1.setText(_translate("TicTacToe", "1"))
        self.pushButton_2.setText(_translate("TicTacToe", "2"))
        self.pushButton_3.setText(_translate("TicTacToe", "3"))
        self.pushButton_4.setText(_translate("TicTacToe", "4"))
        self.pushButton_5.setText(_translate("TicTacToe", "5"))
        self.pushButton_6.setText(_translate("TicTacToe", "6"))
        self.pushButton_7.setText(_translate("TicTacToe", "7"))
        self.pushButton_8.setText(_translate("TicTacToe", "8"))
        self.pushButton_9.setText(_translate("TicTacToe", "9"))


if __name__ == "__main__":
    import sys
    
    app = QtWidgets.QApplication(sys.argv)
    
    TicTacToe = QtWidgets.QWidget()
    ui = Ui_TicTacToe()
    ui.setupUi(TicTacToe)
    
    TicTacToe.show()
    
    sys.exit(app.exec_())
